# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emsodev_dmp_api.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mw_emsodev(object):
    def setupUi(self, mw_emsodev):
        mw_emsodev.setObjectName(_fromUtf8("mw_emsodev"))
        mw_emsodev.resize(1528, 368)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mw_emsodev.sizePolicy().hasHeightForWidth())
        mw_emsodev.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(mw_emsodev)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gb_connection = QtGui.QGroupBox(self.centralwidget)
        self.gb_connection.setMinimumSize(QtCore.QSize(220, 0))
        self.gb_connection.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gb_connection.setFont(font)
        self.gb_connection.setObjectName(_fromUtf8("gb_connection"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.gb_connection)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.le_login = QtGui.QLineEdit(self.gb_connection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_login.sizePolicy().hasHeightForWidth())
        self.le_login.setSizePolicy(sizePolicy)
        self.le_login.setMinimumSize(QtCore.QSize(200, 0))
        self.le_login.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_login.setFont(font)
        self.le_login.setInputMask(_fromUtf8(""))
        self.le_login.setText(_fromUtf8(""))
        self.le_login.setObjectName(_fromUtf8("le_login"))
        self.verticalLayout_6.addWidget(self.le_login)
        self.le_password = QtGui.QLineEdit(self.gb_connection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_password.sizePolicy().hasHeightForWidth())
        self.le_password.setSizePolicy(sizePolicy)
        self.le_password.setMinimumSize(QtCore.QSize(200, 0))
        self.le_password.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_password.setFont(font)
        self.le_password.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.le_password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.le_password.setObjectName(_fromUtf8("le_password"))
        self.verticalLayout_6.addWidget(self.le_password)
        self.pb_connect = QtGui.QPushButton(self.gb_connection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_connect.sizePolicy().hasHeightForWidth())
        self.pb_connect.setSizePolicy(sizePolicy)
        self.pb_connect.setMinimumSize(QtCore.QSize(200, 0))
        self.pb_connect.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_connect.setFont(font)
        self.pb_connect.setObjectName(_fromUtf8("pb_connect"))
        self.verticalLayout_6.addWidget(self.pb_connect)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.gb_connection)
        self.gb_observatories = QtGui.QGroupBox(self.centralwidget)
        self.gb_observatories.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gb_observatories.setFont(font)
        self.gb_observatories.setObjectName(_fromUtf8("gb_observatories"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gb_observatories)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lw_observatories = QtGui.QListWidget(self.gb_observatories)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lw_observatories.sizePolicy().hasHeightForWidth())
        self.lw_observatories.setSizePolicy(sizePolicy)
        self.lw_observatories.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lw_observatories.setObjectName(_fromUtf8("lw_observatories"))
        self.verticalLayout_2.addWidget(self.lw_observatories)
        self.horizontalLayout.addWidget(self.gb_observatories)
        self.gb_instruments = QtGui.QGroupBox(self.centralwidget)
        self.gb_instruments.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gb_instruments.setFont(font)
        self.gb_instruments.setObjectName(_fromUtf8("gb_instruments"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gb_instruments)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lw_instruments = QtGui.QListWidget(self.gb_instruments)
        self.lw_instruments.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lw_instruments.setObjectName(_fromUtf8("lw_instruments"))
        self.verticalLayout_3.addWidget(self.lw_instruments)
        self.horizontalLayout.addWidget(self.gb_instruments)
        self.gb_parameters = QtGui.QGroupBox(self.centralwidget)
        self.gb_parameters.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gb_parameters.setFont(font)
        self.gb_parameters.setObjectName(_fromUtf8("gb_parameters"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gb_parameters)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lw_parameters = QtGui.QListWidget(self.gb_parameters)
        self.lw_parameters.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lw_parameters.setObjectName(_fromUtf8("lw_parameters"))
        self.verticalLayout_4.addWidget(self.lw_parameters)
        self.horizontalLayout.addWidget(self.gb_parameters)
        self.gb_dates = QtGui.QGroupBox(self.centralwidget)
        self.gb_dates.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gb_dates.setFont(font)
        self.gb_dates.setObjectName(_fromUtf8("gb_dates"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.gb_dates)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.rb_start = QtGui.QRadioButton(self.gb_dates)
        self.rb_start.setChecked(True)
        self.rb_start.setObjectName(_fromUtf8("rb_start"))
        self.horizontalLayout_4.addWidget(self.rb_start)
        self.rb_end = QtGui.QRadioButton(self.gb_dates)
        self.rb_end.setObjectName(_fromUtf8("rb_end"))
        self.horizontalLayout_4.addWidget(self.rb_end)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.calendar = QtGui.QCalendarWidget(self.gb_dates)
        self.calendar.setObjectName(_fromUtf8("calendar"))
        self.verticalLayout_5.addWidget(self.calendar)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.l_start_title = QtGui.QLabel(self.gb_dates)
        self.l_start_title.setObjectName(_fromUtf8("l_start_title"))
        self.horizontalLayout_2.addWidget(self.l_start_title)
        self.l_start = QtGui.QLabel(self.gb_dates)
        self.l_start.setObjectName(_fromUtf8("l_start"))
        self.horizontalLayout_2.addWidget(self.l_start)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.l_end_title = QtGui.QLabel(self.gb_dates)
        self.l_end_title.setObjectName(_fromUtf8("l_end_title"))
        self.horizontalLayout_3.addWidget(self.l_end_title)
        self.l_stop = QtGui.QLabel(self.gb_dates)
        self.l_stop.setObjectName(_fromUtf8("l_stop"))
        self.horizontalLayout_3.addWidget(self.l_stop)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addWidget(self.gb_dates)
        self.vl_buttons = QtGui.QVBoxLayout()
        self.vl_buttons.setObjectName(_fromUtf8("vl_buttons"))
        self.pb_download = QtGui.QPushButton(self.centralwidget)
        self.pb_download.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_download.setFont(font)
        self.pb_download.setObjectName(_fromUtf8("pb_download"))
        self.vl_buttons.addWidget(self.pb_download)
        self.pb_save = QtGui.QPushButton(self.centralwidget)
        self.pb_save.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_save.setFont(font)
        self.pb_save.setObjectName(_fromUtf8("pb_save"))
        self.vl_buttons.addWidget(self.pb_save)
        self.horizontalLayout.addLayout(self.vl_buttons)
        mw_emsodev.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(mw_emsodev)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mw_emsodev.setStatusBar(self.statusbar)

        self.retranslateUi(mw_emsodev)
        QtCore.QMetaObject.connectSlotsByName(mw_emsodev)

    def retranslateUi(self, mw_emsodev):
        mw_emsodev.setWindowTitle(_translate("mw_emsodev", "Download EMSO data", None))
        self.gb_connection.setTitle(_translate("mw_emsodev", "Connection to EMSOdev", None))
        self.le_login.setPlaceholderText(_translate("mw_emsodev", "login", None))
        self.le_password.setPlaceholderText(_translate("mw_emsodev", "password", None))
        self.pb_connect.setText(_translate("mw_emsodev", "Connect", None))
        self.gb_observatories.setTitle(_translate("mw_emsodev", "Observatories", None))
        self.gb_instruments.setTitle(_translate("mw_emsodev", "Instruments", None))
        self.gb_parameters.setTitle(_translate("mw_emsodev", "Parameters", None))
        self.gb_dates.setTitle(_translate("mw_emsodev", "Dates", None))
        self.rb_start.setText(_translate("mw_emsodev", "Start", None))
        self.rb_end.setText(_translate("mw_emsodev", "End", None))
        self.l_start_title.setText(_translate("mw_emsodev", "Start date: ", None))
        self.l_start.setText(_translate("mw_emsodev", "???", None))
        self.l_end_title.setText(_translate("mw_emsodev", "End date: ", None))
        self.l_stop.setText(_translate("mw_emsodev", "Now", None))
        self.pb_download.setText(_translate("mw_emsodev", "Download", None))
        self.pb_save.setText(_translate("mw_emsodev", "Save .pkl file", None))

