# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1057, 775)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(_fromUtf8("background-color: white;"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.plot_and_options = QtGui.QVBoxLayout()
        self.plot_and_options.setObjectName(_fromUtf8("plot_and_options"))
        self.slicing_layout_2 = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slicing_layout_2.sizePolicy().hasHeightForWidth())
        self.slicing_layout_2.setSizePolicy(sizePolicy)
        self.slicing_layout_2.setObjectName(_fromUtf8("slicing_layout_2"))
        self.slicing_layout = QtGui.QHBoxLayout(self.slicing_layout_2)
        self.slicing_layout.setObjectName(_fromUtf8("slicing_layout"))
        self.slicing_start_label = QtGui.QLabel(self.slicing_layout_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slicing_start_label.sizePolicy().hasHeightForWidth())
        self.slicing_start_label.setSizePolicy(sizePolicy)
        self.slicing_start_label.setObjectName(_fromUtf8("slicing_start_label"))
        self.slicing_layout.addWidget(self.slicing_start_label)
        self.slicing_start_time = QtGui.QDateTimeEdit(self.slicing_layout_2)
        self.slicing_start_time.setObjectName(_fromUtf8("slicing_start_time"))
        self.slicing_layout.addWidget(self.slicing_start_time)
        self.slicing_stop_label = QtGui.QLabel(self.slicing_layout_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slicing_stop_label.sizePolicy().hasHeightForWidth())
        self.slicing_stop_label.setSizePolicy(sizePolicy)
        self.slicing_stop_label.setObjectName(_fromUtf8("slicing_stop_label"))
        self.slicing_layout.addWidget(self.slicing_stop_label)
        self.slicing_end_time = QtGui.QDateTimeEdit(self.slicing_layout_2)
        self.slicing_end_time.setObjectName(_fromUtf8("slicing_end_time"))
        self.slicing_layout.addWidget(self.slicing_end_time)
        self.slicing_accept_button = QtGui.QPushButton(self.slicing_layout_2)
        self.slicing_accept_button.setObjectName(_fromUtf8("slicing_accept_button"))
        self.slicing_layout.addWidget(self.slicing_accept_button)
        self.slicing_cancel_button = QtGui.QPushButton(self.slicing_layout_2)
        self.slicing_cancel_button.setObjectName(_fromUtf8("slicing_cancel_button"))
        self.slicing_layout.addWidget(self.slicing_cancel_button)
        self.plot_and_options.addWidget(self.slicing_layout_2)
        self.plot_window = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_window.sizePolicy().hasHeightForWidth())
        self.plot_window.setSizePolicy(sizePolicy)
        self.plot_window.setObjectName(_fromUtf8("plot_window"))
        self.plot_vertical_layout = QtGui.QVBoxLayout(self.plot_window)
        self.plot_vertical_layout.setObjectName(_fromUtf8("plot_vertical_layout"))
        self.plot_and_options.addWidget(self.plot_window)
        self.horizontalLayout.addLayout(self.plot_and_options)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.title_platform_code = QtGui.QLabel(self.centralwidget)
        self.title_platform_code.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.title_platform_code.setFont(font)
        self.title_platform_code.setObjectName(_fromUtf8("title_platform_code"))
        self.verticalLayout.addWidget(self.title_platform_code)
        self.platform_code = QtGui.QLabel(self.centralwidget)
        self.platform_code.setStyleSheet(_fromUtf8(""))
        self.platform_code.setObjectName(_fromUtf8("platform_code"))
        self.verticalLayout.addWidget(self.platform_code)
        self.title_wmo_code = QtGui.QLabel(self.centralwidget)
        self.title_wmo_code.setObjectName(_fromUtf8("title_wmo_code"))
        self.verticalLayout.addWidget(self.title_wmo_code)
        self.wmo_code = QtGui.QLabel(self.centralwidget)
        self.wmo_code.setObjectName(_fromUtf8("wmo_code"))
        self.verticalLayout.addWidget(self.wmo_code)
        self.title_institution = QtGui.QLabel(self.centralwidget)
        self.title_institution.setObjectName(_fromUtf8("title_institution"))
        self.verticalLayout.addWidget(self.title_institution)
        self.institution = QtGui.QLabel(self.centralwidget)
        self.institution.setObjectName(_fromUtf8("institution"))
        self.verticalLayout.addWidget(self.institution)
        self.title_assembly_center = QtGui.QLabel(self.centralwidget)
        self.title_assembly_center.setObjectName(_fromUtf8("title_assembly_center"))
        self.verticalLayout.addWidget(self.title_assembly_center)
        self.assembly_center = QtGui.QLabel(self.centralwidget)
        self.assembly_center.setObjectName(_fromUtf8("assembly_center"))
        self.verticalLayout.addWidget(self.assembly_center)
        self.title_type = QtGui.QLabel(self.centralwidget)
        self.title_type.setObjectName(_fromUtf8("title_type"))
        self.verticalLayout.addWidget(self.title_type)
        self.type = QtGui.QLabel(self.centralwidget)
        self.type.setObjectName(_fromUtf8("type"))
        self.verticalLayout.addWidget(self.type)
        self.title_plots = QtGui.QLabel(self.centralwidget)
        self.title_plots.setObjectName(_fromUtf8("title_plots"))
        self.verticalLayout.addWidget(self.title_plots)
        self.title_above = QtGui.QLabel(self.centralwidget)
        self.title_above.setObjectName(_fromUtf8("title_above"))
        self.verticalLayout.addWidget(self.title_above)
        self.above_list = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.above_list.sizePolicy().hasHeightForWidth())
        self.above_list.setSizePolicy(sizePolicy)
        self.above_list.setMaximumSize(QtCore.QSize(150, 16777215))
        self.above_list.setObjectName(_fromUtf8("above_list"))
        self.verticalLayout.addWidget(self.above_list)
        self.title_under = QtGui.QLabel(self.centralwidget)
        self.title_under.setObjectName(_fromUtf8("title_under"))
        self.verticalLayout.addWidget(self.title_under)
        self.under_list = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.under_list.sizePolicy().hasHeightForWidth())
        self.under_list.setSizePolicy(sizePolicy)
        self.under_list.setMaximumSize(QtCore.QSize(150, 16777215))
        self.under_list.setObjectName(_fromUtf8("under_list"))
        self.verticalLayout.addWidget(self.under_list)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1057, 21))
        self.menubar.setStyleSheet(_fromUtf8("selection-color: rgb(0, 0, 255);"))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setStyleSheet(_fromUtf8("selection-color: rgb(0, 0, 255);"))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuPlot_stype = QtGui.QMenu(self.menuSettings)
        self.menuPlot_stype.setObjectName(_fromUtf8("menuPlot_stype"))
        self.menuReport = QtGui.QMenu(self.menubar)
        self.menuReport.setObjectName(_fromUtf8("menuReport"))
        self.menuData = QtGui.QMenu(self.menubar)
        self.menuData.setObjectName(_fromUtf8("menuData"))
        self.menuResample = QtGui.QMenu(self.menuData)
        self.menuResample.setObjectName(_fromUtf8("menuResample"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenData = QtGui.QAction(MainWindow)
        self.actionOpenData.setObjectName(_fromUtf8("actionOpenData"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSaveToDoc = QtGui.QAction(MainWindow)
        self.actionSaveToDoc.setObjectName(_fromUtf8("actionSaveToDoc"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionBmh = QtGui.QAction(MainWindow)
        self.actionBmh.setObjectName(_fromUtf8("actionBmh"))
        self.actionClassic = QtGui.QAction(MainWindow)
        self.actionClassic.setObjectName(_fromUtf8("actionClassic"))
        self.actionDark_background = QtGui.QAction(MainWindow)
        self.actionDark_background.setObjectName(_fromUtf8("actionDark_background"))
        self.actionFivethirtyeight = QtGui.QAction(MainWindow)
        self.actionFivethirtyeight.setObjectName(_fromUtf8("actionFivethirtyeight"))
        self.actionGgplot = QtGui.QAction(MainWindow)
        self.actionGgplot.setObjectName(_fromUtf8("actionGgplot"))
        self.actionGrayscale = QtGui.QAction(MainWindow)
        self.actionGrayscale.setObjectName(_fromUtf8("actionGrayscale"))
        self.actionSeaborn_bright = QtGui.QAction(MainWindow)
        self.actionSeaborn_bright.setObjectName(_fromUtf8("actionSeaborn_bright"))
        self.actionSeaborn_colorblind = QtGui.QAction(MainWindow)
        self.actionSeaborn_colorblind.setObjectName(_fromUtf8("actionSeaborn_colorblind"))
        self.actionSeaborn_dark = QtGui.QAction(MainWindow)
        self.actionSeaborn_dark.setObjectName(_fromUtf8("actionSeaborn_dark"))
        self.actionSeaborn_dark_palette = QtGui.QAction(MainWindow)
        self.actionSeaborn_dark_palette.setObjectName(_fromUtf8("actionSeaborn_dark_palette"))
        self.actionSeaborn_darkgrid = QtGui.QAction(MainWindow)
        self.actionSeaborn_darkgrid.setObjectName(_fromUtf8("actionSeaborn_darkgrid"))
        self.actionSeaborn_deep = QtGui.QAction(MainWindow)
        self.actionSeaborn_deep.setObjectName(_fromUtf8("actionSeaborn_deep"))
        self.actionSeaborn_muted = QtGui.QAction(MainWindow)
        self.actionSeaborn_muted.setObjectName(_fromUtf8("actionSeaborn_muted"))
        self.actionSeaborn_notebook = QtGui.QAction(MainWindow)
        self.actionSeaborn_notebook.setObjectName(_fromUtf8("actionSeaborn_notebook"))
        self.actionSeaborn_paper = QtGui.QAction(MainWindow)
        self.actionSeaborn_paper.setObjectName(_fromUtf8("actionSeaborn_paper"))
        self.actionSeaborn_pastel = QtGui.QAction(MainWindow)
        self.actionSeaborn_pastel.setObjectName(_fromUtf8("actionSeaborn_pastel"))
        self.actionSeaborn_poster = QtGui.QAction(MainWindow)
        self.actionSeaborn_poster.setObjectName(_fromUtf8("actionSeaborn_poster"))
        self.actionSeaborn_talk = QtGui.QAction(MainWindow)
        self.actionSeaborn_talk.setObjectName(_fromUtf8("actionSeaborn_talk"))
        self.actionSeaborn_triks = QtGui.QAction(MainWindow)
        self.actionSeaborn_triks.setObjectName(_fromUtf8("actionSeaborn_triks"))
        self.actionSeaborn_white = QtGui.QAction(MainWindow)
        self.actionSeaborn_white.setObjectName(_fromUtf8("actionSeaborn_white"))
        self.actionSeaborn_whitegrid = QtGui.QAction(MainWindow)
        self.actionSeaborn_whitegrid.setObjectName(_fromUtf8("actionSeaborn_whitegrid"))
        self.actionXkcd = QtGui.QAction(MainWindow)
        self.actionXkcd.setObjectName(_fromUtf8("actionXkcd"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSlicing = QtGui.QAction(MainWindow)
        self.actionSlicing.setObjectName(_fromUtf8("actionSlicing"))
        self.actionDay_frequency = QtGui.QAction(MainWindow)
        self.actionDay_frequency.setObjectName(_fromUtf8("actionDay_frequency"))
        self.actionWeekly_frequency = QtGui.QAction(MainWindow)
        self.actionWeekly_frequency.setObjectName(_fromUtf8("actionWeekly_frequency"))
        self.actionMonth_frequency = QtGui.QAction(MainWindow)
        self.actionMonth_frequency.setObjectName(_fromUtf8("actionMonth_frequency"))
        self.actionHourly_frequency = QtGui.QAction(MainWindow)
        self.actionHourly_frequency.setObjectName(_fromUtf8("actionHourly_frequency"))
        self.menuFile.addAction(self.actionOpenData)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuPlot_stype.addAction(self.actionBmh)
        self.menuPlot_stype.addAction(self.actionClassic)
        self.menuPlot_stype.addAction(self.actionDark_background)
        self.menuPlot_stype.addAction(self.actionFivethirtyeight)
        self.menuPlot_stype.addAction(self.actionGgplot)
        self.menuPlot_stype.addAction(self.actionGrayscale)
        self.menuPlot_stype.addAction(self.actionSeaborn_bright)
        self.menuPlot_stype.addAction(self.actionSeaborn_colorblind)
        self.menuPlot_stype.addAction(self.actionSeaborn_dark)
        self.menuPlot_stype.addAction(self.actionSeaborn_dark_palette)
        self.menuPlot_stype.addAction(self.actionSeaborn_darkgrid)
        self.menuPlot_stype.addAction(self.actionSeaborn_deep)
        self.menuPlot_stype.addAction(self.actionSeaborn_muted)
        self.menuPlot_stype.addAction(self.actionSeaborn_notebook)
        self.menuPlot_stype.addAction(self.actionSeaborn_paper)
        self.menuPlot_stype.addAction(self.actionSeaborn_pastel)
        self.menuPlot_stype.addAction(self.actionSeaborn_poster)
        self.menuPlot_stype.addAction(self.actionSeaborn_talk)
        self.menuPlot_stype.addAction(self.actionSeaborn_triks)
        self.menuPlot_stype.addAction(self.actionSeaborn_white)
        self.menuPlot_stype.addAction(self.actionSeaborn_whitegrid)
        self.menuPlot_stype.addSeparator()
        self.menuPlot_stype.addAction(self.actionXkcd)
        self.menuSettings.addAction(self.menuPlot_stype.menuAction())
        self.menuSettings.addAction(self.actionPreferences)
        self.menuReport.addAction(self.actionSave_as)
        self.menuReport.addAction(self.actionSave)
        self.menuResample.addAction(self.actionMonth_frequency)
        self.menuResample.addAction(self.actionWeekly_frequency)
        self.menuResample.addAction(self.actionDay_frequency)
        self.menuResample.addAction(self.actionHourly_frequency)
        self.menuData.addAction(self.menuResample.menuAction())
        self.menuData.addAction(self.actionSlicing)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MOODA EMODnet", None))
        self.slicing_start_label.setText(_translate("MainWindow", "Start: ", None))
        self.slicing_stop_label.setText(_translate("MainWindow", "End: ", None))
        self.slicing_accept_button.setText(_translate("MainWindow", "Accept", None))
        self.slicing_cancel_button.setText(_translate("MainWindow", "Cancel", None))
        self.title_platform_code.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0000ff;\">PLATFORM CODE</span></p></body></html>", None))
        self.platform_code.setText(_translate("MainWindow", "??", None))
        self.title_wmo_code.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0000ff;\">WMO CODE</span></p></body></html>", None))
        self.wmo_code.setText(_translate("MainWindow", "??", None))
        self.title_institution.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0000ff;\">INSTITUTION</span></p></body></html>", None))
        self.institution.setText(_translate("MainWindow", "??", None))
        self.title_assembly_center.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0000ff;\">ASSEMBLY CENTER</span></p></body></html>", None))
        self.assembly_center.setText(_translate("MainWindow", "??", None))
        self.title_type.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0000ff;\">TYPE</span></p></body></html>", None))
        self.type.setText(_translate("MainWindow", "??", None))
        self.title_plots.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0000ff;\">PLOTS</span></p></body></html>", None))
        self.title_above.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#0000ff;\">Above the sea surface</span></p></body></html>", None))
        self.title_under.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#0000ff;\">Under the sea surface</span></p></body></html>", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.menuPlot_stype.setTitle(_translate("MainWindow", "Plot style", None))
        self.menuReport.setTitle(_translate("MainWindow", "Report", None))
        self.menuData.setTitle(_translate("MainWindow", "Data", None))
        self.menuResample.setTitle(_translate("MainWindow", "Resample", None))
        self.actionOpenData.setText(_translate("MainWindow", "Open data", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionSaveToDoc.setText(_translate("MainWindow", "Save to doc", None))
        self.actionSaveToDoc.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences...", None))
        self.actionBmh.setText(_translate("MainWindow", "bmh", None))
        self.actionClassic.setText(_translate("MainWindow", "classic", None))
        self.actionDark_background.setText(_translate("MainWindow", "dark background", None))
        self.actionFivethirtyeight.setText(_translate("MainWindow", "fivethirtyeight", None))
        self.actionGgplot.setText(_translate("MainWindow", "ggplot", None))
        self.actionGrayscale.setText(_translate("MainWindow", "grayscale", None))
        self.actionSeaborn_bright.setText(_translate("MainWindow", "seaborn bright    ", None))
        self.actionSeaborn_colorblind.setText(_translate("MainWindow", "seaborn colorblind    ", None))
        self.actionSeaborn_dark.setText(_translate("MainWindow", "seaborn dark", None))
        self.actionSeaborn_dark_palette.setText(_translate("MainWindow", "seaborn dark palette", None))
        self.actionSeaborn_darkgrid.setText(_translate("MainWindow", "seaborn darkgrid", None))
        self.actionSeaborn_deep.setText(_translate("MainWindow", "seaborn deep", None))
        self.actionSeaborn_muted.setText(_translate("MainWindow", "seaborn muted", None))
        self.actionSeaborn_notebook.setText(_translate("MainWindow", "seaborn notebook", None))
        self.actionSeaborn_paper.setText(_translate("MainWindow", "seaborn paper", None))
        self.actionSeaborn_pastel.setText(_translate("MainWindow", "seaborn pastel", None))
        self.actionSeaborn_poster.setText(_translate("MainWindow", "seaborn poster", None))
        self.actionSeaborn_talk.setText(_translate("MainWindow", "seaborn talk", None))
        self.actionSeaborn_triks.setText(_translate("MainWindow", "seaborn triks", None))
        self.actionSeaborn_white.setText(_translate("MainWindow", "seaborn white", None))
        self.actionSeaborn_whitegrid.setText(_translate("MainWindow", "seaborn whitegrid", None))
        self.actionXkcd.setText(_translate("MainWindow", "xkcd", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save as...", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionSlicing.setText(_translate("MainWindow", "Slicing", None))
        self.actionDay_frequency.setText(_translate("MainWindow", "Day frequency", None))
        self.actionWeekly_frequency.setText(_translate("MainWindow", "Weekly frequency", None))
        self.actionMonth_frequency.setText(_translate("MainWindow", "Month frequency", None))
        self.actionHourly_frequency.setText(_translate("MainWindow", "Hourly frequency", None))

