# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mooda.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mooda_window(object):
    def setupUi(self, mooda_window):
        mooda_window.setObjectName(_fromUtf8("mooda_window"))
        mooda_window.resize(918, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/mooda.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mooda_window.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(mooda_window)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.w_egim = QtGui.QWidget(self.centralwidget)
        self.w_egim.setEnabled(False)
        self.w_egim.setObjectName(_fromUtf8("w_egim"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.w_egim)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gb_observatories = QtGui.QGroupBox(self.w_egim)
        self.gb_observatories.setObjectName(_fromUtf8("gb_observatories"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gb_observatories)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lw_observatories = QtGui.QListWidget(self.gb_observatories)
        self.lw_observatories.setObjectName(_fromUtf8("lw_observatories"))
        self.verticalLayout_2.addWidget(self.lw_observatories)
        self.cb_observatories = QtGui.QCheckBox(self.gb_observatories)
        self.cb_observatories.setObjectName(_fromUtf8("cb_observatories"))
        self.verticalLayout_2.addWidget(self.cb_observatories)
        self.horizontalLayout.addWidget(self.gb_observatories)
        self.gb_instruments = QtGui.QGroupBox(self.w_egim)
        self.gb_instruments.setEnabled(False)
        self.gb_instruments.setObjectName(_fromUtf8("gb_instruments"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.gb_instruments)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.lw_instruments = QtGui.QListWidget(self.gb_instruments)
        self.lw_instruments.setObjectName(_fromUtf8("lw_instruments"))
        self.verticalLayout_5.addWidget(self.lw_instruments)
        self.cb_instruments = QtGui.QCheckBox(self.gb_instruments)
        self.cb_instruments.setObjectName(_fromUtf8("cb_instruments"))
        self.verticalLayout_5.addWidget(self.cb_instruments)
        self.horizontalLayout.addWidget(self.gb_instruments)
        self.gb_parameters = QtGui.QGroupBox(self.w_egim)
        self.gb_parameters.setEnabled(False)
        self.gb_parameters.setObjectName(_fromUtf8("gb_parameters"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gb_parameters)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lw_parameters = QtGui.QListWidget(self.gb_parameters)
        self.lw_parameters.setObjectName(_fromUtf8("lw_parameters"))
        self.verticalLayout_3.addWidget(self.lw_parameters)
        self.cb_parameters = QtGui.QCheckBox(self.gb_parameters)
        self.cb_parameters.setObjectName(_fromUtf8("cb_parameters"))
        self.verticalLayout_3.addWidget(self.cb_parameters)
        self.horizontalLayout.addWidget(self.gb_parameters)
        self.vl_dates_actions = QtGui.QVBoxLayout()
        self.vl_dates_actions.setObjectName(_fromUtf8("vl_dates_actions"))
        self.gb_dates = QtGui.QGroupBox(self.w_egim)
        self.gb_dates.setEnabled(False)
        self.gb_dates.setObjectName(_fromUtf8("gb_dates"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gb_dates)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.hl_start_date = QtGui.QHBoxLayout()
        self.hl_start_date.setObjectName(_fromUtf8("hl_start_date"))
        self.l_start_date = QtGui.QLabel(self.gb_dates)
        self.l_start_date.setObjectName(_fromUtf8("l_start_date"))
        self.hl_start_date.addWidget(self.l_start_date)
        self.de_start_date = QtGui.QDateEdit(self.gb_dates)
        self.de_start_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 1, 27), QtCore.QTime(0, 0, 0)))
        self.de_start_date.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2017, 1, 27), QtCore.QTime(0, 0, 0)))
        self.de_start_date.setCalendarPopup(True)
        self.de_start_date.setObjectName(_fromUtf8("de_start_date"))
        self.hl_start_date.addWidget(self.de_start_date)
        self.verticalLayout_4.addLayout(self.hl_start_date)
        self.hl_end_date = QtGui.QHBoxLayout()
        self.hl_end_date.setObjectName(_fromUtf8("hl_end_date"))
        self.l_end_date = QtGui.QLabel(self.gb_dates)
        self.l_end_date.setObjectName(_fromUtf8("l_end_date"))
        self.hl_end_date.addWidget(self.l_end_date)
        self.de_end_date = QtGui.QDateEdit(self.gb_dates)
        self.de_end_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 1, 28), QtCore.QTime(0, 0, 0)))
        self.de_end_date.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2017, 1, 28), QtCore.QTime(0, 0, 0)))
        self.de_end_date.setCalendarPopup(True)
        self.de_end_date.setObjectName(_fromUtf8("de_end_date"))
        self.hl_end_date.addWidget(self.de_end_date)
        self.verticalLayout_4.addLayout(self.hl_end_date)
        self.vl_dates_actions.addWidget(self.gb_dates)
        self.pb_download = QtGui.QPushButton(self.w_egim)
        self.pb_download.setEnabled(False)
        self.pb_download.setObjectName(_fromUtf8("pb_download"))
        self.vl_dates_actions.addWidget(self.pb_download)
        self.pb_save = QtGui.QPushButton(self.w_egim)
        self.pb_save.setEnabled(False)
        self.pb_save.setObjectName(_fromUtf8("pb_save"))
        self.vl_dates_actions.addWidget(self.pb_save)
        self.pb_close_egim = QtGui.QPushButton(self.w_egim)
        self.pb_close_egim.setObjectName(_fromUtf8("pb_close_egim"))
        self.vl_dates_actions.addWidget(self.pb_close_egim)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vl_dates_actions.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.vl_dates_actions)
        self.verticalLayout.addWidget(self.w_egim)
        self.w_results = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_results.sizePolicy().hasHeightForWidth())
        self.w_results.setSizePolicy(sizePolicy)
        self.w_results.setMinimumSize(QtCore.QSize(0, 0))
        self.w_results.setObjectName(_fromUtf8("w_results"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.w_results)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.w_inspector = QtGui.QWidget(self.w_results)
        self.w_inspector.setMinimumSize(QtCore.QSize(0, 0))
        self.w_inspector.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.w_inspector.setBaseSize(QtCore.QSize(0, 0))
        self.w_inspector.setObjectName(_fromUtf8("w_inspector"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.w_inspector)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.w_tree = QtGui.QTreeWidget(self.w_inspector)
        self.w_tree.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.w_tree.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.w_tree.setObjectName(_fromUtf8("w_tree"))
        self.w_tree.headerItem().setText(0, _fromUtf8("1"))
        self.w_tree.header().setMinimumSectionSize(1800)
        self.w_tree.header().setSortIndicatorShown(False)
        self.w_tree.header().setStretchLastSection(True)
        self.verticalLayout_6.addWidget(self.w_tree)
        self.cb_join = QtGui.QCheckBox(self.w_inspector)
        self.cb_join.setObjectName(_fromUtf8("cb_join"))
        self.verticalLayout_6.addWidget(self.cb_join)
        self.cb_qc1 = QtGui.QCheckBox(self.w_inspector)
        self.cb_qc1.setObjectName(_fromUtf8("cb_qc1"))
        self.verticalLayout_6.addWidget(self.cb_qc1)
        self.pb_plot = QtGui.QPushButton(self.w_inspector)
        self.pb_plot.setObjectName(_fromUtf8("pb_plot"))
        self.verticalLayout_6.addWidget(self.pb_plot)
        self.horizontalLayout_2.addWidget(self.w_inspector)
        self.w_plot = QtGui.QWidget(self.w_results)
        self.w_plot.setMinimumSize(QtCore.QSize(0, 0))
        self.w_plot.setBaseSize(QtCore.QSize(0, 0))
        self.w_plot.setObjectName(_fromUtf8("w_plot"))
        self.vl_plot = QtGui.QVBoxLayout(self.w_plot)
        self.vl_plot.setObjectName(_fromUtf8("vl_plot"))
        self.horizontalLayout_2.addWidget(self.w_plot)
        self.verticalLayout.addWidget(self.w_results)
        self.pte_text = QtGui.QPlainTextEdit(self.centralwidget)
        self.pte_text.setObjectName(_fromUtf8("pte_text"))
        self.verticalLayout.addWidget(self.pte_text)
        mooda_window.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mooda_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 918, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.m_file = QtGui.QMenu(self.menubar)
        self.m_file.setStatusTip(_fromUtf8(""))
        self.m_file.setObjectName(_fromUtf8("m_file"))
        self.m_recent_data = QtGui.QMenu(self.m_file)
        self.m_recent_data.setObjectName(_fromUtf8("m_recent_data"))
        self.m_help = QtGui.QMenu(self.menubar)
        self.m_help.setObjectName(_fromUtf8("m_help"))
        self.m_view = QtGui.QMenu(self.menubar)
        self.m_view.setObjectName(_fromUtf8("m_view"))
        self.menu_settings = QtGui.QMenu(self.menubar)
        self.menu_settings.setObjectName(_fromUtf8("menu_settings"))
        self.a_number = QtGui.QMenu(self.menu_settings)
        self.a_number.setObjectName(_fromUtf8("a_number"))
        self.menuPlot_style = QtGui.QMenu(self.menu_settings)
        self.menuPlot_style.setObjectName(_fromUtf8("menuPlot_style"))
        self.m_data = QtGui.QMenu(self.menubar)
        self.m_data.setObjectName(_fromUtf8("m_data"))
        self.menuAverage = QtGui.QMenu(self.m_data)
        self.menuAverage.setStatusTip(_fromUtf8(""))
        self.menuAverage.setObjectName(_fromUtf8("menuAverage"))
        mooda_window.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mooda_window)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mooda_window.setStatusBar(self.statusbar)
        self.a_open = QtGui.QAction(mooda_window)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.a_open.setIcon(icon1)
        self.a_open.setStatusTip(_fromUtf8(""))
        self.a_open.setObjectName(_fromUtf8("a_open"))
        self.a_save_as = QtGui.QAction(mooda_window)
        self.a_save_as.setStatusTip(_fromUtf8(""))
        self.a_save_as.setObjectName(_fromUtf8("a_save_as"))
        self.a_save = QtGui.QAction(mooda_window)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.a_save.setIcon(icon2)
        self.a_save.setStatusTip(_fromUtf8(""))
        self.a_save.setObjectName(_fromUtf8("a_save"))
        self.a_download = QtGui.QAction(mooda_window)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/download.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.a_download.setIcon(icon3)
        self.a_download.setStatusTip(_fromUtf8(""))
        self.a_download.setObjectName(_fromUtf8("a_download"))
        self.a_close = QtGui.QAction(mooda_window)
        self.a_close.setStatusTip(_fromUtf8(""))
        self.a_close.setVisible(True)
        self.a_close.setObjectName(_fromUtf8("a_close"))
        self.a_quit = QtGui.QAction(mooda_window)
        self.a_quit.setStatusTip(_fromUtf8(""))
        self.a_quit.setObjectName(_fromUtf8("a_quit"))
        self.a_save_log = QtGui.QAction(mooda_window)
        self.a_save_log.setStatusTip(_fromUtf8(""))
        self.a_save_log.setObjectName(_fromUtf8("a_save_log"))
        self.a_logbook = QtGui.QAction(mooda_window)
        self.a_logbook.setCheckable(True)
        self.a_logbook.setObjectName(_fromUtf8("a_logbook"))
        self.a_egim_downloader = QtGui.QAction(mooda_window)
        self.a_egim_downloader.setCheckable(True)
        self.a_egim_downloader.setVisible(True)
        self.a_egim_downloader.setObjectName(_fromUtf8("a_egim_downloader"))
        self.a_data_inspector = QtGui.QAction(mooda_window)
        self.a_data_inspector.setCheckable(True)
        self.a_data_inspector.setObjectName(_fromUtf8("a_data_inspector"))
        self.a_1 = QtGui.QAction(mooda_window)
        self.a_1.setCheckable(True)
        self.a_1.setChecked(True)
        self.a_1.setObjectName(_fromUtf8("a_1"))
        self.a_2 = QtGui.QAction(mooda_window)
        self.a_2.setCheckable(True)
        self.a_2.setObjectName(_fromUtf8("a_2"))
        self.a_bmh = QtGui.QAction(mooda_window)
        self.a_bmh.setCheckable(True)
        self.a_bmh.setObjectName(_fromUtf8("a_bmh"))
        self.a_classic = QtGui.QAction(mooda_window)
        self.a_classic.setCheckable(True)
        self.a_classic.setObjectName(_fromUtf8("a_classic"))
        self.a_dark = QtGui.QAction(mooda_window)
        self.a_dark.setCheckable(True)
        self.a_dark.setObjectName(_fromUtf8("a_dark"))
        self.a_fivethirtyeight = QtGui.QAction(mooda_window)
        self.a_fivethirtyeight.setCheckable(True)
        self.a_fivethirtyeight.setObjectName(_fromUtf8("a_fivethirtyeight"))
        self.a_ggplot = QtGui.QAction(mooda_window)
        self.a_ggplot.setCheckable(True)
        self.a_ggplot.setChecked(True)
        self.a_ggplot.setObjectName(_fromUtf8("a_ggplot"))
        self.a_grayscale = QtGui.QAction(mooda_window)
        self.a_grayscale.setCheckable(True)
        self.a_grayscale.setObjectName(_fromUtf8("a_grayscale"))
        self.a_seaborn = QtGui.QAction(mooda_window)
        self.a_seaborn.setCheckable(True)
        self.a_seaborn.setObjectName(_fromUtf8("a_seaborn"))
        self.a_qc = QtGui.QAction(mooda_window)
        self.a_qc.setStatusTip(_fromUtf8(""))
        self.a_qc.setObjectName(_fromUtf8("a_qc"))
        self.a_hourly = QtGui.QAction(mooda_window)
        self.a_hourly.setCheckable(True)
        self.a_hourly.setObjectName(_fromUtf8("a_hourly"))
        self.a_daily = QtGui.QAction(mooda_window)
        self.a_daily.setCheckable(True)
        self.a_daily.setObjectName(_fromUtf8("a_daily"))
        self.a_none = QtGui.QAction(mooda_window)
        self.a_none.setCheckable(True)
        self.a_none.setChecked(True)
        self.a_none.setObjectName(_fromUtf8("a_none"))
        self.a_minutely = QtGui.QAction(mooda_window)
        self.a_minutely.setCheckable(True)
        self.a_minutely.setObjectName(_fromUtf8("a_minutely"))
        self.a_weekely = QtGui.QAction(mooda_window)
        self.a_weekely.setCheckable(True)
        self.a_weekely.setObjectName(_fromUtf8("a_weekely"))
        self.action = QtGui.QAction(mooda_window)
        self.action.setObjectName(_fromUtf8("action"))
        self.a_about = QtGui.QAction(mooda_window)
        self.a_about.setObjectName(_fromUtf8("a_about"))
        self.actionOnline_documentation = QtGui.QAction(mooda_window)
        self.actionOnline_documentation.setObjectName(_fromUtf8("actionOnline_documentation"))
        self.m_file.addAction(self.a_open)
        self.m_file.addAction(self.a_download)
        self.m_file.addAction(self.m_recent_data.menuAction())
        self.m_file.addSeparator()
        self.m_file.addAction(self.a_save)
        self.m_file.addAction(self.a_save_as)
        self.m_file.addSeparator()
        self.m_file.addAction(self.a_save_log)
        self.m_file.addSeparator()
        self.m_file.addAction(self.a_close)
        self.m_file.addSeparator()
        self.m_file.addAction(self.a_quit)
        self.m_help.addAction(self.a_about)
        self.m_view.addAction(self.a_egim_downloader)
        self.m_view.addAction(self.a_logbook)
        self.m_view.addAction(self.a_data_inspector)
        self.a_number.addAction(self.a_1)
        self.a_number.addAction(self.a_2)
        self.menuPlot_style.addAction(self.a_bmh)
        self.menuPlot_style.addAction(self.a_classic)
        self.menuPlot_style.addAction(self.a_dark)
        self.menuPlot_style.addAction(self.a_fivethirtyeight)
        self.menuPlot_style.addAction(self.a_ggplot)
        self.menuPlot_style.addAction(self.a_grayscale)
        self.menuPlot_style.addAction(self.a_seaborn)
        self.menu_settings.addAction(self.menuPlot_style.menuAction())
        self.menu_settings.addAction(self.a_number.menuAction())
        self.menuAverage.addAction(self.a_none)
        self.menuAverage.addAction(self.a_minutely)
        self.menuAverage.addAction(self.a_hourly)
        self.menuAverage.addAction(self.a_daily)
        self.menuAverage.addAction(self.a_weekely)
        self.m_data.addAction(self.a_qc)
        self.m_data.addAction(self.menuAverage.menuAction())
        self.menubar.addAction(self.m_file.menuAction())
        self.menubar.addAction(self.m_data.menuAction())
        self.menubar.addAction(self.m_view.menuAction())
        self.menubar.addAction(self.menu_settings.menuAction())
        self.menubar.addAction(self.m_help.menuAction())

        self.retranslateUi(mooda_window)
        QtCore.QMetaObject.connectSlotsByName(mooda_window)

    def retranslateUi(self, mooda_window):
        mooda_window.setWindowTitle(_translate("mooda_window", "MOODA", None))
        self.gb_observatories.setTitle(_translate("mooda_window", "Observatories", None))
        self.cb_observatories.setText(_translate("mooda_window", "All", None))
        self.gb_instruments.setTitle(_translate("mooda_window", "Instruments", None))
        self.cb_instruments.setText(_translate("mooda_window", "All", None))
        self.gb_parameters.setTitle(_translate("mooda_window", "Parameters", None))
        self.cb_parameters.setText(_translate("mooda_window", "All", None))
        self.gb_dates.setTitle(_translate("mooda_window", "Dates", None))
        self.l_start_date.setText(_translate("mooda_window", "Start", None))
        self.l_end_date.setText(_translate("mooda_window", "End", None))
        self.pb_download.setText(_translate("mooda_window", "Download", None))
        self.pb_save.setText(_translate("mooda_window", "Save", None))
        self.pb_close_egim.setText(_translate("mooda_window", "Close", None))
        self.cb_join.setText(_translate("mooda_window", "Join similar parameters", None))
        self.cb_qc1.setText(_translate("mooda_window", "Only QC 1", None))
        self.pb_plot.setText(_translate("mooda_window", "Plot", None))
        self.m_file.setTitle(_translate("mooda_window", "File", None))
        self.m_recent_data.setTitle(_translate("mooda_window", "Recent data", None))
        self.m_help.setTitle(_translate("mooda_window", "Help", None))
        self.m_view.setTitle(_translate("mooda_window", "View", None))
        self.menu_settings.setTitle(_translate("mooda_window", "Settings", None))
        self.a_number.setTitle(_translate("mooda_window", "Number of plots", None))
        self.menuPlot_style.setTitle(_translate("mooda_window", "Plot style", None))
        self.m_data.setTitle(_translate("mooda_window", "Data", None))
        self.menuAverage.setTitle(_translate("mooda_window", "Average", None))
        self.a_open.setText(_translate("mooda_window", "Open...", None))
        self.a_open.setShortcut(_translate("mooda_window", "Ctrl+O", None))
        self.a_save_as.setText(_translate("mooda_window", "Save as...", None))
        self.a_save.setText(_translate("mooda_window", "Save", None))
        self.a_save.setShortcut(_translate("mooda_window", "Ctrl+S", None))
        self.a_download.setText(_translate("mooda_window", "Download data", None))
        self.a_close.setText(_translate("mooda_window", "Close", None))
        self.a_close.setShortcut(_translate("mooda_window", "Ctrl+F4", None))
        self.a_quit.setText(_translate("mooda_window", "Quit", None))
        self.a_save_log.setText(_translate("mooda_window", "Save log", None))
        self.a_logbook.setText(_translate("mooda_window", "Logbook", None))
        self.a_logbook.setShortcut(_translate("mooda_window", "Ctrl+L", None))
        self.a_egim_downloader.setText(_translate("mooda_window", "EGIM Downloader", None))
        self.a_data_inspector.setText(_translate("mooda_window", "Data inspector", None))
        self.a_1.setText(_translate("mooda_window", "1", None))
        self.a_2.setText(_translate("mooda_window", "2", None))
        self.a_bmh.setText(_translate("mooda_window", "bmh", None))
        self.a_classic.setText(_translate("mooda_window", "classic", None))
        self.a_dark.setText(_translate("mooda_window", "dark background", None))
        self.a_fivethirtyeight.setText(_translate("mooda_window", "fivethirtyeight", None))
        self.a_ggplot.setText(_translate("mooda_window", "ggplot", None))
        self.a_grayscale.setText(_translate("mooda_window", "grayscale", None))
        self.a_seaborn.setText(_translate("mooda_window", "seaborn", None))
        self.a_qc.setText(_translate("mooda_window", "QC generation", None))
        self.a_hourly.setText(_translate("mooda_window", "Hourly", None))
        self.a_daily.setText(_translate("mooda_window", "Daily", None))
        self.a_none.setText(_translate("mooda_window", "None", None))
        self.a_minutely.setText(_translate("mooda_window", "Minutely", None))
        self.a_weekely.setText(_translate("mooda_window", "Weekly", None))
        self.action.setText(_translate("mooda_window", ".", None))
        self.a_about.setText(_translate("mooda_window", "About", None))
        self.actionOnline_documentation.setText(_translate("mooda_window", "Online documentation", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    mooda_window = QtGui.QMainWindow()
    ui = Ui_mooda_window()
    ui.setupUi(mooda_window)
    mooda_window.show()
    sys.exit(app.exec_())

